class Keylight < Formula
  desc "Manage Keylight apps, licenses, and integrations from the terminal"
  homepage "https://keylight.dev"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # Prebuilt binaries where they are published, source builds everywhere else.
  # The crate is `keylight-cli`; the binary it installs is `keylight`.
  on_macos do
    on_arm do
      url "https://github.com/keylight-dev/keylight-cli/releases/download/v0.2.2/keylight-aarch64-apple-darwin"
      sha256 "3ded79562f064198a0c0244c6f059824f8031fb969f25e49ef32bec472fe0a10"
    end

    on_intel do
      url "https://github.com/keylight-dev/keylight-cli/releases/download/v0.2.2/keylight-x86_64-apple-darwin"
      sha256 "0fd1475050535a45403dbf92235eef0260802c70caef11b77a96b0ac27640f5e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/keylight-dev/keylight-cli/releases/download/v0.2.2/keylight-x86_64-unknown-linux-gnu"
      sha256 "10b1c32287c10d42399bd861109e7306271d485e3c79408d5922248c30db2a77"
    end

    on_arm do
      url "https://static.crates.io/crates/keylight-cli/keylight-cli-0.2.2.crate"
      sha256 "dc219ec9be5de4ee3576ec8229079203b7193e5a3cb285dd7cbdde91295990cd"
      depends_on "rust" => :build
    end
  end

  # Bottles are built by the tap's CI on pull requests and published by
  # `brew pr-pull`. They matter more than usual here: without one, brew takes the
  # build-from-source path, which enforces a minimum Xcode for the running macOS
  # and hard-fails when the installed Xcode is older — an error about Xcode, on a
  # machine that only wanted a licensing CLI.

  def install
    # The source archive has a Cargo.toml; a downloaded release binary does not.
    if File.exist?("Cargo.toml")
      system "cargo", "install", *std_cargo_args
    else
      # A bare binary arrives 0644 from the release asset, so set the mode
      # rather than assuming an archive preserved it.
      bin.install Dir["keylight-*"].first => "keylight"
      chmod 0755, bin/"keylight"
    end

    # Shell completions and a man page, generated by the binary itself.
    generate_completions_from_executable(bin/"keylight", "completions")
    (man1/"keylight.1").write Utils.safe_popen_read(bin/"keylight", "man")
  end

  test do
    assert_match "keylight #{version}", shell_output("#{bin}/keylight --version")
    assert_match "Usage: keylight", shell_output("#{bin}/keylight --help")

    # No command may block on a prompt — that is the property the whole CLI
    # rests on. Unauthenticated, it must exit 2 rather than ask for anything.
    output = shell_output("#{bin}/keylight auth status 2>&1", 2)
    assert_match "no API token configured", output
  end
end
